common_rsync_options="--no-motd --timeout 14400"
max_propagation_days = 2
max_stale_days = 3
excludes=[".*\\.snapshot", ".*/\\.~tmp~"]
skip_paths_for_version=["pub/alt"]
test_paths=["/test/", "/stage/"]
skip_repository_paths = ["Cloud", "Workstation", "Server", "rpi/33/src", "rpi/34/src"]
do_not_display_paths = ["_Beta"]

[database]
url="postgresql://localhost/mmtest"

[[category]]
name="RPMFUSION nonfree EL"
type="rsync"
url="rsync://download1.rpmfusion.org/rpmfusion/nonfree/el/"
checksum_base="https://download1.rpmfusion.org/"

[[category]]
name="RPMFUSION free EL"
type="rsync"
url="rsync://download1.rpmfusion.org/rpmfusion/free/el/"
options="--exclude=nothing --port=873"
checksum_base="https://download1.rpmfusion.org/"
excludes=["somethingsomething"]

[[category]]
name="RPMFUSION free Fedora"
type="rsync"
url="rsync://lisas.de/rpmfusion/free/fedora/"
options="--exclude=nothing --port=873"
checksum_base="https://ftp-stud.hs-esslingen.de/pub/Mirrors/rpmfusion.org/"

[[repository_mapping]]
regex="^free/fedora/updates/[\\.\\d]+/.*"
prefix="free-fedora-updates-released"

[[repository_mapping]]
regex="^free/fedora/updates/testing/[\\.\\d]+/.*"
prefix="free-fedora-updates-testing"

[[repository_mapping]]
regex="^free/fedora/tainted/[\\.\\d]+/.*"
prefix="free-fedora-tainted"

[[repository_mapping]]
regex="^free/fedora/rpi/[\\.\\d]+/.*"
prefix="free-fedora-rpi"

[[repository_mapping]]
regex="^free/el/rpi/[\\.\\d]+/.*"
prefix="free-el-rpi"

[[repository_mapping]]
regex="^free/el/tainted/[\\.\\d]+/.*"
prefix="free-el-tainted"

[[repository_mapping]]
regex="^nonfree/el/tainted/[\\.\\d]+/.*"
prefix="nonfree-el-tainted"

[[repository_mapping]]
regex="^free/el/updates/[\\.\\d]+/.*"
prefix="free-el-updates-released"

[[repository_mapping]]
regex="^free/el/updates/testing/[\\.\\d]+/.*"
prefix="free-el-updates-testing"

[[repository_mapping]]
regex="^free/el/releases/[\\.\\d]+/.*"
prefix="free-el"

[[repository_mapping]]
regex="^nonfree/el/updates/[\\.\\d]+/.*"
prefix="nonfree-el-updates-released"

[[repository_mapping]]
regex="^nonfree/el/updates/testing/[\\.\\d]+/.*"
prefix="nonfree-el-updates-testing"

[[repository_mapping]]
regex="^nonfree/el/releases/[\\.\\d]+/.*"
prefix="nonfree-el"

[[repository_mapping]]
regex="^free/fedora/(releases|development)/(rawhide|[\\.\\d]+)/.*"
prefix="free-fedora"
