common_rsync_options="--no-motd --timeout 14400"
max_propagation_days = 2
max_stale_days = 3
excludes=[".*\\.snapshot", ".*/\\.~tmp~"]
skip_paths_for_version=["pub/alt"]
test_paths=["/test/", "/stage/"]
skip_repository_paths = ["Cloud", "Workstation", "Server", "rpi/33/src", "rpi/34/src"]
do_not_display_paths = ["_Beta"]

[database]
url="postgresql://localhost/mmtest"

[[category]]
name="RPMFUSION nonfree EL"
type="directory"
url="/home/adrian/rpmfusion/nonfree/el/"
checksum_base="https://download1.rpmfusion.org/"

[[category]]
name="RPMFUSION free EL"
type="rsync"
url="rsync://download1.rpmfusion.org/rpmfusion/free/el/"
options="--exclude=nothing --port=873"
checksum_base="https://download1.rpmfusion.org/"
excludes=["somethingsomething"]

[[category]]
name="RPMFUSION free Fedora"
type="rsync"
url="rsync://lisas.de/rpmfusion/free/fedora/"
options="--exclude=nothing --port=873"
checksum_base="https://ftp-stud.hs-esslingen.de/pub/Mirrors/rpmfusion.org/"

[[category]]
name="RPMFUSION nonfree Fedora"
type="rsync"
url="rsync://lisas.de/rpmfusion/nonfree/fedora/"
options="--port=873"
checksum_base="https://ftp-stud.hs-esslingen.de/pub/Mirrors/rpmfusion.org/"

[[category]]
name="RPMFUSION free Fedora Secondary"
type="rsync"
url="rsync://lisas.de/rpmfusion/free/fedora-secondary/"
options="--exclude=nothing --port=873"
checksum_base="https://ftp-stud.hs-esslingen.de/pub/Mirrors/rpmfusion.org/"

[[category]]
name="RPMFUSION nonfree Fedora Secondary"
type="rsync"
url="rsync://lisas.de/rpmfusion/nonfree/fedora-secondary/"
options="--exclude=nothing --port=873"
checksum_base="https://ftp-stud.hs-esslingen.de/pub/Mirrors/rpmfusion.org/"

[[category]]
name="RPMFUSION nonfree EL Archive"
type="rsync"
url="rsync://mirror1.hs-esslingen.de/archive.rpmfusion.org/free-archive/el/"
checksum_base="https://mirror1.hs-esslingen.de/pub/Mirrors/archive.rpmfusion.org/"

[[category]]
name="RPMFUSION free EL Archive"
type="rsync"
url="rsync://mirror1.hs-esslingen.de/archive.rpmfusion.org/nonfree-archive/el/"
checksum_base="https://mirror1.hs-esslingen.de/pub/Mirrors/archive.rpmfusion.org/"

[[category]]
name="RPMFUSION free Fedora Archive"
type="rsync"
url="rsync://mirror1.hs-esslingen.de/archive.rpmfusion.org/free-archive/fedora/"
checksum_base="https://mirror1.hs-esslingen.de/pub/Mirrors/archive.rpmfusion.org/"

[[category]]
name="RPMFUSION nonfree Fedora Archive"
type="rsync"
url="rsync://mirror1.hs-esslingen.de/archive.rpmfusion.org/nonfree-archive/fedora/"
checksum_base="https://mirror1.hs-esslingen.de/pub/Mirrors/archive.rpmfusion.org/"

[[category]]
name="RPMFUSION free Fedora Secondary Archive"
type="rsync"
url="rsync://mirror1.hs-esslingen.de/archive.rpmfusion.org/free-archive/fedora-secondary/"
checksum_base="https://mirror1.hs-esslingen.de/pub/Mirrors/archive.rpmfusion.org/"

[[category]]
name="RPMFUSION nonfree Fedora Secondary Archive"
type="rsync"
url="rsync://mirror1.hs-esslingen.de/archive.rpmfusion.org/nonfree-archive/fedora-secondary/"
checksum_base="https://mirror1.hs-esslingen.de/pub/Mirrors/archive.rpmfusion.org/"

[[repository_mapping]]
regex="^nonfree(-archive)?/fedora(-secondary)?/updates/[\\.\\d]+/.*"
prefix="nonfree-fedora-updates-released"

[[repository_mapping]]
regex="^nonfree(-archive)?/fedora(-secondary)?/updates/testing/[\\.\\d]+/.*"
prefix="nonfree-fedora-updates-testing"

[[repository_mapping]]
regex="^free(-archive)?/fedora(-secondary)?/updates/[\\.\\d]+/.*"
prefix="free-fedora-updates-released"

[[repository_mapping]]
regex="^free(-archive)?/fedora(-secondary)?/updates/testing/[\\.\\d]+/.*"
prefix="free-fedora-updates-testing"

[[repository_mapping]]
regex="^free(-archive)?/fedora/tainted/[\\.\\d]+/.*"
prefix="free-fedora-tainted"

[[repository_mapping]]
regex="^nonfree(-archive)?/fedora/tainted/[\\.\\d]+/.*"
prefix="nonfree-fedora-tainted"

[[repository_mapping]]
regex="^nonfree(-archive)?/fedora/steam/[\\.\\d]+/.*"
prefix="nonfree-fedora-steam"

[[repository_mapping]]
regex="^free(-archive)?/fedora/rpi/[\\.\\d]+/.*"
prefix="free-fedora-rpi"

[[repository_mapping]]
regex="^nonfree(-archive)?/fedora/nvidia-driver/[\\.\\d]+/.*"
prefix="nonfree-fedora-nvidia-driver"

[[repository_mapping]]
regex="^free(-archive)?/fedora/drivers/[\\.\\d]+/.*"
prefix="free-fedora-drivers"

[[repository_mapping]]
regex="nonfree(-archive)?/fedora/drivers/[\\.\\d]+/.*"
prefix="nonfree-fedora-drivers"

[[repository_mapping]]
regex="^free(-archive)?/el/rpi/[\\.\\d]+/.*"
prefix="free-el-rpi"

[[repository_mapping]]
regex="^free(-archive)?/el/tainted/[\\.\\d]+/.*"
prefix="free-el-tainted"

[[repository_mapping]]
regex="^nonfree(-archive)?/el/tainted/[\\.\\d]+/.*"
prefix="nonfree-el-tainted"

[[repository_mapping]]
regex="^free(-archive)?/el/updates/[\\.\\d]+/.*"
prefix="free-el-updates-released"

[[repository_mapping]]
regex="^free(-archive)?/el/updates/testing/[\\.\\d]+/.*"
prefix="free-el-updates-testing"

[[repository_mapping]]
regex="^free(-archive)?/el/releases/[\\.\\d]+/.*"
prefix="free-el"

[[repository_mapping]]
regex="^nonfree(-archive)?/el/updates/[\\.\\d]+/.*"
prefix="nonfree-el-updates-released"

[[repository_mapping]]
regex="^nonfree(-archive)?/el/updates/testing/[\\.\\d]+/.*"
prefix="nonfree-el-updates-testing"

[[repository_mapping]]
regex="^nonfree(-archive)?/el/releases/[\\.\\d]+/.*"
prefix="nonfree-el"

[[repository_mapping]]
regex="^free(-archive)?/fedora(-secondary)?/(releases|development)/(rawhide|[\\.\\d]+)/.*"
prefix="free-fedora"

[[repository_mapping]]
regex="^nonfree(-archive)?/fedora(-secondary)?/(releases|development)/(rawhide|[\\.\\d]+)/.*"
prefix="nonfree-fedora"

[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/(releases|development)/(rawhide|[\\.\\d]+)/.*"
prefix="fedora"

[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/updates/[\\.\\d]+/Everything/.*"
prefix="updates-released"

[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/updates/[\\.\\d]+/Modular/.*"
prefix="updates-released-modular"

[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/updates/testing/[\\.\\d]+/Everything/.*"
prefix="updates-testing"

[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/updates/testing/[\\.\\d]+/Modular/.*"
prefix="updates-testing-modular"

# pre modular structure
[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/updates/testing/([\\.\\d]+)/[^ME].*"
prefix="updates-testing"

[[repository_mapping]]
regex="^pub/archive/fedora(-secondary)?(/linux)?/updates/([\\.\\d]+)/[^ME].*"
prefix="updates-released"


